apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Porta dentro do cluster
      targetPort: 8000 # Porta do container FastAPI
      nodePort: 30080 # Porta do Raspberry Pi
