name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build e push da imagem
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME